const TYPES=['all','prompts','skills','agents','workflows','solutions','templates','images','videos'];
const LABELS={all:'All assets',prompts:'Prompts',skills:'Skills',agents:'Agents',workflows:'Workflows',solutions:'Solutions',templates:'Templates',images:'Images',videos:'Videos'};
let assets=[], activeType='all', lang='en';
const $=s=>document.querySelector(s);
async function load(){const lists=await Promise.all(TYPES.slice(1).map(t=>fetch(`../registry/${t}.json`).then(r=>r.json()))); assets=lists.flat(); renderTabs(); populateCategories(); render(); $('#assetCount').textContent=`${assets.length} original assets and growing`;}
function renderTabs(){ $('#typeTabs').innerHTML=TYPES.map(t=>`<button class="type-tab ${t===activeType?'active':''}" data-type="${t}" role="tab">${LABELS[t]}</button>`).join(''); document.querySelectorAll('.type-tab').forEach(b=>b.onclick=()=>{activeType=b.dataset.type;renderTabs();render();}); }
function populateCategories(){const cats=[...new Set(assets.map(a=>a.category))].sort(); $('#categoryFilter').innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join('');}
function filtered(){const q=$('#search').value.toLowerCase().trim(), cat=$('#categoryFilter').value, status=$('#statusFilter').value, sort=$('#sort').value; let out=assets.filter(a=>(activeType==='all'||a.type+'s'===activeType)&&(!q||[a.name,a.description,a.category,...a.tags].join(' ').toLowerCase().includes(q))&&(!cat||a.category===cat)&&(!status||a.status===status)); return out.sort((a,b)=>sort==='az'?a.name.localeCompare(b.name):sort==='rating'?(b.rating||0)-(a.rating||0):sort==='recent'?b.updated_at.localeCompare(a.updated_at):(b.tests||0)-(a.tests||0));}
function render(){const out=filtered();$('#resultsCount').textContent=`${out.length} asset${out.length===1?'':'s'} found`;$('#emptyState').hidden=out.length>0;$('#assetGrid').innerHTML=out.map(card).join('');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openAsset(b.dataset.open));}
function card(a){return `<article class="asset-card"><div class="asset-card-top"><span class="asset-type">${a.type} ${a.verified?'· ✓ verified':''}</span><span>v${a.version}</span></div><h3>${a.name}</h3><p>${a.description}</p><div class="tags">${a.tags.slice(0,3).map(t=>`<span class="tag">#${t}</span>`).join('')}</div><div class="asset-card-bottom"><span>★ ${(a.rating||0).toFixed(1)} · ${a.tests||0} tests</span><span>${a.license}</span></div><div class="asset-actions"><button class="small-button" data-open="${a.id}">${a.type==='template'?'Use template':'Preview'} →</button><button class="small-button outline" data-open="${a.id}">Test</button></div></article>`;}
function openAsset(id){const a=assets.find(x=>x.id===id);if(!a)return;const isTemplate=a.type==='template'||a.variables;$('#modalContent').innerHTML=`<div class="modal-kicker">${a.type} · ${a.verified?'verified · ':''}v${a.version}</div><h2 id="modalTitle">${a.name}</h2><p>${a.description}</p><div class="modal-meta"><span>★ ${(a.rating||0).toFixed(1)} rating</span><span>${a.tests||0} tests</span><span>${a.license}</span><span>${(a.compatibility||[]).slice(0,2).join(' · ')}</span></div>${isTemplate?formFor(a):`<div class="preview-box">${a.name}

Ready to preview and test.

Source: ${a.source}
Lineage: original asset · ${a.version}</div><div class="modal-actions"><button class="button primary" onclick="showToast('Test fixture saved locally')">Run test <span>→</span></button><button class="button secondary" onclick="showToast('Asset copied to clipboard')">Copy asset</button></div>`}`;$('#assetModal').hidden=false;}
function formFor(a){return `<p><strong>Use Template</strong> creates a new version. The original <b>${a.id}</b> will not be modified.</p><form class="variable-form" id="templateForm">${(a.variables||[]).map(v=>`<label>${v.name.replaceAll('_',' ')}${v.required?' *':''}<small>${v.description}</small>${v.type==='long-text'?`<textarea name="${v.name}" rows="3" ${v.required?'required':''}>${v.default||''}</textarea>`:`<input name="${v.name}" value="${v.default||''}" ${v.required?'required':''}>`}</label>`).join('')}<div class="modal-actions"><button class="button primary" type="submit">Preview customized version <span>→</span></button></div></form><div id="customPreview"></div>`;}
document.addEventListener('submit',e=>{if(e.target.id!=='templateForm')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.target));$('#customPreview').innerHTML=`<div class="preview-box">Customized preview

${Object.entries(data).map(([k,v])=>`${k}: ${v}`).join('
')}

Lineage: based on template · new local version 1.0.0-custom
No source asset was modified.</div><div class="modal-actions"><button type="button" class="button primary" onclick="showToast('Saved as a local fork with lineage')">Save as my version</button><button type="button" class="button secondary" onclick="navigator.clipboard?.writeText(JSON.stringify(${JSON.stringify(data)}));showToast('Copied')">Copy</button></div>`;});
function showToast(msg){const t=document.createElement('div');t.textContent=msg;t.style='position:fixed;bottom:25px;left:50%;transform:translateX(-50%);background:#13241f;color:#fff;padding:12px 18px;border-radius:5px;font-size:12px;z-index:40';document.body.append(t);setTimeout(()=>t.remove(),2200);}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('#assetModal').hidden=true);$('#search').oninput=render;$('#sort').onchange=render;$('#categoryFilter').onchange=render;$('#statusFilter').onchange=render;$('#filterToggle').onclick=()=>$('#filterPanel').hidden=!$('#filterPanel').hidden;$('#clearFilters').onclick=()=>{$('#categoryFilter').value='';$('#statusFilter').value='';$('#search').value='';render();};$('#createAsset').onclick=()=>{location.hash='contribute';showToast('Start with the contribution guide on GitHub');};$('#langToggle').onclick=()=>{lang=lang==='en'?'ar':'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('rtl',lang==='ar');$('#langToggle').textContent=lang==='ar'?'English':'عربي';};load();
